config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: 'index'
  get 'tasks/new', to: 'tasks#new', as: 'new'
  post 'tasks', to: 'tasks#create'

  # NB: The `show` route needs to be *after* `new` route.
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get    'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch  'tasks/:id',      to: 'tasks#update'

  delete 'tasks/:id',      to: 'tasks#destroy', as: 'delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to index_path
  end

  def show
    set_task
  end

  def update
    set_task
    @task.update(task_params)
    redirect_to index_path(@task)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    set_task
  end

  def destroy
    set_task
    @task.destroy
    redirect_to index_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit Task </h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :details %><br>
  <%= f.text_field :details %><br>
  <%= f.check_box :completed %>
  <%= f.label :completed %><br>
  <%= f.submit %><br>
<% end %>

app/views/tasks/index.html.erb
<h1> My Tasks </h1>

<% @tasks.each do |task| %>
<div>
  <% if task.completed %>
    <i class="far fa-check-square"></i>
  <% else %>
    <i class="far fa-square"></i>
  <% end %>
  <%= link_to task.title, task_path(task) %>
  <%= link_to "Delete", delete_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</div>
<% end %>
<br>
<%= link_to "Add a new task", new_path %>

app/views/tasks/new.html.erb
<h1> New Task </h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :details %><br>
  <%= f.text_field :details %><br>
  <%= f.submit %><br>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed == true %>
  <input type= "checkbox" checked> This task is completed <br>
<% else %>
  <input type= "checkbox" > This task is not completed yet <br>
<% end %>
<br>
<%= link_to "Back to list", index_path %><br>

<%= link_to "Edit this task", edit_path(@task) %><br>